Hw02 fix app
kotecreate/hw-test pull request #10
Opened 2024-05-31 11:16 UTC by kotecreate

fix

2024-05-31 11:28 UTC, vladislavmass requested changes

2024-05-31 11:28 UTC, vladislavmass commented on hw02_fix_app/go.mod
>  module github.com/fixme_my_friend/hw02_fix_app
Имя модуля тоже надо пофиксить

2024-05-31 11:28 UTC, vladislavmass commented on hw02_fix_app/printer/pkg.go
>  		fmt.Println(str)
Тут бы хватило и `fmt.Println(staff[i])`. Именно что бы работала такая конструкция мы делали у `types.Employee` метод `String`

2024-05-31 11:28 UTC, vladislavmass commented on hw02_fix_app/reader/pkg.go
>  		fmt.Printf("Error: %v", err)
Не хватает возврата ошибки. `return nil,err` Вряд ли чтение не открытого файла приведет к чему то хорошему

2024-05-31 11:28 UTC, vladislavmass commented on hw02_fix_app/reader/pkg.go
> +func ReadJSON(filePath string, _ int) ([]types.Employee, error) {
Правильнее было бы сделать `func ReadJSON(filePath string) ([]types.Employee, error)` . Трюк _ нужен тогда, когда нужно поддержать интерфейс

2024-05-31 11:28 UTC, vladislavmass commented on hw02_fix_app/reader/pkg.go
>  	res := data
Эта строка лишняя. Можно сразу вернуть data

2024-05-31 12:31 UTC, kotecreate commented on hw02_fix_app/printer/pkg.go
>  		fmt.Println(str)
Исправил

2024-05-31 12:31 UTC, kotecreate commented on hw02_fix_app/reader/pkg.go
>  		fmt.Printf("Error: %v", err)
Исправил

2024-05-31 12:31 UTC, kotecreate commented on hw02_fix_app/reader/pkg.go
> +func ReadJSON(filePath string, _ int) ([]types.Employee, error) {
исправил

2024-05-31 12:31 UTC, kotecreate commented on hw02_fix_app/reader/pkg.go
>  	res := data
исправил

2024-05-31 12:31 UTC, kotecreate commented on hw02_fix_app/go.mod
>  module github.com/fixme_my_friend/hw02_fix_app
Изменил

2024-05-31 14:59 UTC, vladislavmass requested changes

2024-05-31 14:59 UTC, hungry-honeybadger commented on hw02_fix_app/go.mod
> +module hw-test
Неверное имя модуля. В данном случае верное имя модуля `github.com/kotecreate/hw-test/hw02_fix_app`

2024-06-01 08:42 UTC, kotecreate commented on hw02_fix_app/go.mod
> +module hw-test
Вроде теперь все хорошо

2024-06-02 09:58 UTC, vladislavmass approved these changes
Для первого раза отличная работа

2024-06-02 09:58 UTC, vladislavmass commented on hw02_fix_app/printer/pkg.go
>  		fmt.Println(str)
Очень странна строка. Все, что тут должно быть ` fmt.Println(staff[i])`

2024-06-02 12:48 UTC, merged