ver1
kotecreate/hw-test pull request #11
Opened 2024-06-05 11:54 UTC by kotecreate

2024-06-07 11:20 UTC, vladislavmass requested changes
Код работает не верно.  При вводе числа 7 мы получаем доску 14 на 7, а не 7 на 7

![изображение](https://github.com/kotecreate/hw-test/assets/74667007/d86368f7-7754-4f09-8a17-549e86d6b219)

2024-06-07 11:20 UTC, vladislavmass commented on hw03_chessboard/main.go
> +		if a > 0 && a <= 255 {
Это условие не имеет смысла uint8 не может быть меньше 0 и больше 255. По факту вся эта проверка меняется на `a!=0`. Но и это условие не имеет смысла. 0 это валидное число и можно нарисовать без проблем матрицу 0 на 0

2024-06-07 11:20 UTC, vladislavmass commented on hw03_chessboard/main.go
> +		fmt.Scanf("%v\n", &a)
Тут должно быть `_,err:=fmt.Scanf("%v\n", &a)` и потом обработать err . Тоесть мы получили ошибку ввода и обработали ее

2024-06-07 16:58 UTC, kotecreate commented on hw03_chessboard/main.go
> +		if a > 0 && a <= 255 {
Неправильную работу кода исправил. Немного увлекся переделываением в прошлы раз. Таблица выводится корректно. Про условие подумал логичным, чтобы зациклить до правильного ввода.

2024-06-07 17:05 UTC, kotecreate commented on hw03_chessboard/main.go
> +		fmt.Scanf("%v\n", &a)
Надеюсь правильно понял. Поправил.

2024-06-07 17:31 UTC, vladislavmass requested changes
Доска все еще рисуется некорректно
при вводе цифры 7 должна быть доска 7 на 7
сейчас мы имеем доску 6 на 7
![изображение](https://github.com/kotecreate/hw-test/assets/74667007/7096af73-08f9-4b93-8cc9-f8060481fae2)

2024-06-09 19:53 UTC, vladislavmass approved these changes

2024-06-10 10:40 UTC, merged