Ver 1.1
kotecreate/hw-test pull request #16
Opened 2024-08-12 13:48 UTC by kotecreate

2024-08-12 14:08 UTC, hungry-honeybadger requested changes

2024-08-12 14:08 UTC, hungry-honeybadger commented on hw07_word_counter/main.go
> +	if err != nil {
Я не вижу ситуация при котором сработает этот if так как err нигде не присваивается

2024-08-12 14:08 UTC, vladislavmass commented on hw07_word_counter/main.go
> +		if _, ok := cache[sl[i]]; !ok {
Это if лишний. Можно использовать просто cache[sl[i]]++

2024-08-12 14:08 UTC, vladislavmass commented on hw07_word_counter/main.go
> +	cache := map[string]int{}
Тут лучше использовать make

2024-08-12 14:08 UTC, vladislavmass commented on hw07_word_counter/go.mod
> +module github.com/kotecreate/hw07_word_counter
Неверное имя модуля

2024-08-13 07:14 UTC, kotecreate commented on hw07_word_counter/main.go
> +	if err != nil {
Убрал err

2024-08-13 07:14 UTC, kotecreate commented on hw07_word_counter/main.go
> +		if _, ok := cache[sl[i]]; !ok {
Поправил

2024-08-13 07:14 UTC, kotecreate commented on hw07_word_counter/main.go
> +	cache := map[string]int{}
Изменил

2024-08-13 07:16 UTC, kotecreate commented on hw07_word_counter/go.mod
> +module github.com/kotecreate/hw07_word_counter
Увидел ошибку

2024-08-13 17:55 UTC, vladislavmass requested changes
Работа принята, но с замечанием по качеству кода

2024-08-13 17:55 UTC, vladislavmass commented on hw07_word_counter/main.go
> +	if utf8.ValidString(st); false {
Этот блок кода абсолютно бесполезен так как он всегда false

2024-08-13 17:55 UTC, vladislavmass commented on hw07_word_counter/main.go
> +	if utf8.ValidString(st); false {
Скорее всего тут имелось ввиду ` if !utf8.ValidString(st){` тогда этот блок сработает если строка не валидна

2024-08-14 07:33 UTC, kotecreate commented on hw07_word_counter/main.go
> +	if utf8.ValidString(st); false {
Да, тут перемудрил. Поправил

2024-08-14 08:09 UTC, merged